version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/indexer"
    schedule:
      interval: "weekly"
    groups:
      indexer-dependencies:
        patterns:
          - "*"
